all:
	g++ -I../../../include -o test_contiguous_vectors test_contiguous_vectors.cpp `root-config --cflags --libs`
clean:
	rm -f test_contiguous_vectors test_inputDAC121_pe2_dif_1_1_1_hist.root test_inputDAC121_pe2_dif_1_1_1_tree.root
