#ifndef WG_SCURVE_HPP_
#define WG_SCURVE_HPP_

// system C++ includes
#include <string>

// system C includes
#include <cstdbool>

// user includes
#include "wgConst.hpp"
#include "wgTopology.hpp"

#define SCURVE_SUCCESS              0
#define ERR_CANNOT_CREATE_DIRECTORY 1
#define ERR_WRONG_MODE              2
#define ERR_FAILED_CREATE_XML_FILE  3
#define ERR_WG_SCURVE               4

using namespace std;


// This is needed to call the following functions from Python using ctypes
#ifdef __cplusplus
extern "C" {
#endif
  int wgScurve(const char* x_inputDirName,
               const char* x_outputXMLDirName = "",
               const char* x_outputIMGDirName = "");
#ifdef __cplusplus
}
#endif

void MakeScurveXML(string& outputXMLDir, Topology& topol);
vector<string> GetIncludeFileName(const string& inputDirName);
double Calcurate_Mean(vector<double>);
double Calcurate_Sigma(vector<double>);

DirectoryTreeMapScurve run_directory_tree{ {0, { 0,"iDAC1/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC1/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC1/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC1/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC1/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC1/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC1/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC1/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC1/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC1/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC1/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC1/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC1/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC1/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC1/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC1/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC1/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC1/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC1/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC1/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC1/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC1/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC1/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC1/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC1/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC1/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC1/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC1/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC1/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC1/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC1/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC1/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC1/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC1/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC1/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC1/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC1/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC1/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC1/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC1/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC1/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC1/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC1/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC1/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC1/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC1/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC1/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC1/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC1/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC1/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC1/iThreshold170/wgAnaHistSummary/Xml"}},
																					 {1, { 0,"iDAC2/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC2/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC2/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC2/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC2/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC2/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC2/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC2/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC2/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC2/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC2/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC2/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC2/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC2/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC2/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC2/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC2/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC2/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC2/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC2/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC2/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC2/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC2/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC2/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC2/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC2/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC2/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC2/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC2/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC2/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC2/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC2/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC2/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC2/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC2/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC2/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC2/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC2/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC2/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC2/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC2/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC2/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC2/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC2/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC2/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC2/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC2/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC2/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC2/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC2/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC2/iThreshold170/wgAnaHistSummary/Xml"}},
																					 {2, { 0,"iDAC3/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC3/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC3/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC3/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC3/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC3/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC3/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC3/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC3/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC3/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC3/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC3/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC3/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC3/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC3/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC3/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC3/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC3/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC3/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC3/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC3/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC3/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC3/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC3/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC3/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC3/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC3/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC3/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC3/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC3/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC3/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC3/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC3/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC3/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC3/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC3/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC3/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC3/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC3/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC3/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC3/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC3/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC3/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC3/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC3/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC3/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC3/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC3/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC3/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC3/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC3/iThreshold170/wgAnaHistSummary/Xml"}},
																					 {3, { 0,"iDAC4/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC4/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC4/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC4/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC4/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC4/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC4/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC4/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC4/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC4/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC4/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC4/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC4/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC4/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC4/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC4/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC4/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC4/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC4/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC4/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC4/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC4/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC4/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC4/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC4/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC4/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC4/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC4/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC4/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC4/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC4/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC4/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC4/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC4/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC4/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC4/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC4/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC4/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC4/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC4/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC4/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC4/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC4/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC4/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC4/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC4/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC4/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC4/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC4/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC4/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC4/iThreshold170/wgAnaHistSummary/Xml"}},
																					 {4, { 0,"iDAC5/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC5/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC5/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC5/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC5/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC5/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC5/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC5/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC5/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC5/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC5/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC5/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC5/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC5/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC5/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC5/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC5/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC5/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC5/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC5/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC5/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC5/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC5/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC5/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC5/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC5/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC5/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC5/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC5/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC5/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC5/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC5/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC5/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC5/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC5/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC5/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC5/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC5/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC5/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC5/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC5/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC5/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC5/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC5/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC5/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC5/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC5/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC5/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC5/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC5/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC5/iThreshold170/wgAnaHistSummary/Xml"}},
																					 {5, { 0,"iDAC6/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC6/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC6/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC6/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC6/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC6/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC6/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC6/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC6/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC6/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC6/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC6/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC6/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC6/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC6/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC6/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC6/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC6/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC6/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC6/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC6/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC6/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC6/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC6/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC6/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC6/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC6/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC6/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC6/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC6/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC6/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC6/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC6/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC6/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC6/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC6/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC6/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC6/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC6/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC6/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC6/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC6/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC6/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC6/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC6/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC6/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC6/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC6/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC6/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC6/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC6/iThreshold170/wgAnaHistSummary/Xml"}},
																					 {6, { 0,"iDAC7/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC7/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC7/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC7/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC7/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC7/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC7/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC7/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC7/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC7/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC7/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC7/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC7/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC7/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC7/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC7/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC7/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC7/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC7/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC7/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC7/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC7/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC7/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC7/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC7/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC7/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC7/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC7/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC7/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC7/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC7/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC7/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC7/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC7/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC7/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC7/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC7/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC7/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC7/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC7/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC7/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC7/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC7/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC7/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC7/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC7/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC7/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC7/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC7/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC7/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC7/iThreshold170/wgAnaHistSummary/Xml"}},
																					 {7, { 0,"iDAC8/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC8/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC8/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC8/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC8/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC8/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC8/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC8/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC8/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC8/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC8/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC8/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC8/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC8/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC8/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC8/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC8/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC8/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC8/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC8/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC8/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC8/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC8/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC8/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC8/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC8/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC8/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC8/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC8/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC8/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC8/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC8/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC8/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC8/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC8/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC8/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC8/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC8/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC8/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC8/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC8/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC8/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC8/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC8/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC8/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC8/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC8/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC8/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC8/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC8/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC8/iThreshold170/wgAnaHistSummary/Xml"}},
																					 {8, { 0,"iDAC9/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC9/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC9/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC9/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC9/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC9/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC9/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC9/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC9/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC9/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC9/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC9/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC9/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC9/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC9/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC9/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC9/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC9/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC9/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC9/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC9/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC9/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC9/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC9/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC9/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC9/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC9/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC9/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC9/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC9/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC9/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC9/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC9/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC9/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC9/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC9/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC9/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC9/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC9/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC9/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC9/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC9/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC9/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC9/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC9/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC9/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC9/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC9/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC9/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC9/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC9/iThreshold170/wgAnaHistSummary/Xml"}},
																					 {9, { 0,"iDAC10/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC10/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC10/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC10/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC10/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC10/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC10/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC10/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC10/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC10/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC10/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC10/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC10/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC10/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC10/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC10/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC10/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC10/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC10/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC10/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC10/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC10/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC10/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC10/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC10/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC10/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC10/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC10/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC10/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC10/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC10/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC10/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC10/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC10/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC10/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC10/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC10/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC10/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC10/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC10/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC10/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC10/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC10/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC10/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC10/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC10/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC10/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC10/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC10/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC10/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC10/iThreshold170/wgAnaHistSummary/Xml"}},
																					{10, { 0,"iDAC11/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC11/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC11/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC11/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC11/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC11/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC11/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC11/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC11/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC11/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC11/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC11/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC11/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC11/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC11/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC11/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC11/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC11/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC11/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC11/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC11/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC11/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC11/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC11/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC11/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC11/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC11/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC11/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC11/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC11/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC11/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC11/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC11/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC11/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC11/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC11/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC11/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC11/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC11/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC11/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC11/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC11/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC11/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC11/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC11/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC11/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC11/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC11/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC11/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC11/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC11/iThreshold170/wgAnaHistSummary/Xml"}},
																					{11, { 0,"iDAC12/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC12/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC12/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC12/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC12/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC12/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC12/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC12/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC12/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC12/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC12/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC12/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC12/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC12/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC12/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC12/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC12/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC12/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC12/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC12/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC12/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC12/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC12/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC12/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC12/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC12/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC12/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC12/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC12/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC12/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC12/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC12/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC12/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC12/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC12/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC12/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC12/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC12/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC12/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC12/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC12/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC12/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC12/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC12/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC12/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC12/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC12/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC12/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC12/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC12/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC12/iThreshold170/wgAnaHistSummary/Xml"}},
																					{12, { 0,"iDAC13/iThreshold120/wgAnaHistSummary/Xml"},
																							 { 1,"iDAC13/iThreshold121/wgAnaHistSummary/Xml"},
																							 { 2,"iDAC13/iThreshold122/wgAnaHistSummary/Xml"},
																							 { 3,"iDAC13/iThreshold123/wgAnaHistSummary/Xml"},
																							 { 4,"iDAC13/iThreshold124/wgAnaHistSummary/Xml"},
																							 { 5,"iDAC13/iThreshold125/wgAnaHistSummary/Xml"},
																							 { 6,"iDAC13/iThreshold126/wgAnaHistSummary/Xml"},
																							 { 7,"iDAC13/iThreshold127/wgAnaHistSummary/Xml"},
																							 { 8,"iDAC13/iThreshold128/wgAnaHistSummary/Xml"},
																							 { 9,"iDAC13/iThreshold129/wgAnaHistSummary/Xml"},
																							 {10,"iDAC13/iThreshold130/wgAnaHistSummary/Xml"},
																							 {11,"iDAC13/iThreshold131/wgAnaHistSummary/Xml"},
																							 {12,"iDAC13/iThreshold132/wgAnaHistSummary/Xml"},
																							 {13,"iDAC13/iThreshold133/wgAnaHistSummary/Xml"},
																							 {14,"iDAC13/iThreshold134/wgAnaHistSummary/Xml"},
																							 {15,"iDAC13/iThreshold135/wgAnaHistSummary/Xml"},
																							 {16,"iDAC13/iThreshold136/wgAnaHistSummary/Xml"},
																							 {17,"iDAC13/iThreshold137/wgAnaHistSummary/Xml"},
																							 {18,"iDAC13/iThreshold138/wgAnaHistSummary/Xml"},
																							 {19,"iDAC13/iThreshold139/wgAnaHistSummary/Xml"},
																							 {20,"iDAC13/iThreshold140/wgAnaHistSummary/Xml"},
																							 {21,"iDAC13/iThreshold141/wgAnaHistSummary/Xml"},
																							 {22,"iDAC13/iThreshold142/wgAnaHistSummary/Xml"},
																							 {23,"iDAC13/iThreshold143/wgAnaHistSummary/Xml"},
																							 {24,"iDAC13/iThreshold144/wgAnaHistSummary/Xml"},
																							 {25,"iDAC13/iThreshold145/wgAnaHistSummary/Xml"},
																							 {26,"iDAC13/iThreshold146/wgAnaHistSummary/Xml"},
																							 {27,"iDAC13/iThreshold147/wgAnaHistSummary/Xml"},
																							 {28,"iDAC13/iThreshold148/wgAnaHistSummary/Xml"},
																							 {29,"iDAC13/iThreshold149/wgAnaHistSummary/Xml"},
																							 {30,"iDAC13/iThreshold150/wgAnaHistSummary/Xml"},
																							 {31,"iDAC13/iThreshold151/wgAnaHistSummary/Xml"},
																							 {32,"iDAC13/iThreshold152/wgAnaHistSummary/Xml"},
																							 {33,"iDAC13/iThreshold153/wgAnaHistSummary/Xml"},
																							 {34,"iDAC13/iThreshold154/wgAnaHistSummary/Xml"},
																							 {35,"iDAC13/iThreshold155/wgAnaHistSummary/Xml"},
																							 {36,"iDAC13/iThreshold156/wgAnaHistSummary/Xml"},
																							 {37,"iDAC13/iThreshold157/wgAnaHistSummary/Xml"},
																							 {38,"iDAC13/iThreshold158/wgAnaHistSummary/Xml"},
																							 {39,"iDAC13/iThreshold159/wgAnaHistSummary/Xml"},
																							 {40,"iDAC13/iThreshold160/wgAnaHistSummary/Xml"},
																							 {41,"iDAC13/iThreshold161/wgAnaHistSummary/Xml"},
																							 {42,"iDAC13/iThreshold162/wgAnaHistSummary/Xml"},
																							 {43,"iDAC13/iThreshold163/wgAnaHistSummary/Xml"},
																							 {44,"iDAC13/iThreshold164/wgAnaHistSummary/Xml"},
																							 {45,"iDAC13/iThreshold165/wgAnaHistSummary/Xml"},
																							 {46,"iDAC13/iThreshold166/wgAnaHistSummary/Xml"},
																							 {47,"iDAC13/iThreshold167/wgAnaHistSummary/Xml"},
																							 {48,"iDAC13/iThreshold168/wgAnaHistSummary/Xml"},
																							 {49,"iDAC13/iThreshold169/wgAnaHistSummary/Xml"},
																							 {50,"iDAC13/iThreshold170/wgAnaHistSummary/Xml"}}};

#endif // WG_SCURVE_HPP_
